### ISSUE TITLE
GPU acceleration is not available with AMD graphics cards

### ISSUE THREAD

**Issue by AMDAndy** [Leanny/SeedSearcher#11]
SeedSearcher relies on CUDA for GPU acceleration. AMD has a [tool](https://github.com/ROCm-Developer-Tools/HIP) available to convert CUDA code to convertable C++ code. It might be worth it to try HIP to see if it easily enables SeedSearcher to use GPU acceleration with Radeon GPUs.

**Comment by Leanny** [comment]
I want to switch to OpenCL next in order to be compatible with many more gpus soon. The c# lib I plan to use wants to release a version that supports some features I need in February and I wanted to change to openCL as soon as the update is out.
What I have rn is c# code that basically gets compiled on the fly to Cuda code, so I can't use the converter yet. But I definetly plan to support more gpus with the 1.3 update

**Comment by AMDAndy** [comment]
That's great to hear. We're an all-AMD house and it'd be nice to crunch through those possible seeds quicker.
